file_format: "1"
id: dactyl
Name: dactyl
type: shield
url: https://github.com/bullwinkle3000/zmk-config-xiao/
requires:
  - nice_nano_v2
exposes: 
  - i2c_oled
features:
  - keys
  - display
  - encoders
siblings:
  - dactyl_left
  - dactyl_right
